name: Build, Scan and Deploy .NET App to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  contents: read
  security-events: write  # <-- needed for CodeQL to upload results

jobs:
  build-scan-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # helps CodeQL & PR diffs

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # ----- CodeQL: init FIRST -----
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          # optional: queries: security-extended,security-and-quality

      # ----- Build/Test happen AFTER init so CodeQL can observe them -----
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # (Alternative to the 3 steps above: use this instead of manual build)
      # - name: CodeQL Autobuild (optional)
      #   if: always()  # remove if you use manual build above
      #   uses: github/codeql-action/autobuild@v3

      # ----- CodeQL: analyze LAST -----
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # ----- Publish & Deploy (unchanged) -----
      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: TestRS
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
